version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=niochat
      - POSTGRES_USER=niochat_user
      - POSTGRES_PASSWORD=E0sJT3wAYFuahovmHkxgy
    volumes:
      - niochat-postgres:/var/lib/postgresql/data
    networks:
      - nioNet
    restart: unless-stopped

  # Backend Django - PORTA 8010
  niochat-backend:
    image: ghcr.io/juniorssilvaa/niochat-backend:latest
    environment:
      - SECRET_KEY=OFfGQLqPs5osrBBnhOBdIfkjq1F6vpb74YoAWNkjwbY4BwTNK5
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgresql://niochat_user:E0sJT3wAYFuahovmHkxgy@postgres:5432/niochat
      - MEDIA_URL=/media/
      - STATIC_URL=/static/
      - LOG_LEVEL=DEBUG
    volumes:
      - niochat-media:/app/backend/media
      - niochat-static:/app/backend/staticfiles
    networks:
      - nioNet
    restart: unless-stopped
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      
      # Regra para autenticação - PRIORIDADE MÁXIMA
      - "traefik.http.routers.niochat-backend-auth.rule=Host(`app.niochat.com.br`) && Path(`/api-token-auth/`)"
      - "traefik.http.routers.niochat-backend-auth.entrypoints=websecure"
      - "traefik.http.routers.niochat-backend-auth.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.niochat-backend-auth.priority=300"
      - "traefik.http.routers.niochat-backend-auth.service=niochat-backend-service"
      - "traefik.http.services.niochat-backend-service.loadbalancer.server.port=8010"
      
      # Regra para todas as APIs - PRIORIDADE ALTA
      - "traefik.http.routers.niochat-backend-api.rule=Host(`app.niochat.com.br`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.niochat-backend-api.entrypoints=websecure"
      - "traefik.http.routers.niochat-backend-api.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.niochat-backend-api.priority=200"
      - "traefik.http.routers.niochat-backend-api.service=niochat-backend-service"
      
      # Regra para media files - PRIORIDADE ALTA
      - "traefik.http.routers.niochat-backend-media.rule=Host(`app.niochat.com.br`) && PathPrefix(`/media/`)"
      - "traefik.http.routers.niochat-backend-media.entrypoints=websecure"
      - "traefik.http.routers.niochat-backend-media.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.niochat-backend-media.priority=200"
      - "traefik.http.routers.niochat-backend-media.service=niochat-backend-service"
      
      # Regra para static files - PRIORIDADE ALTA
      - "traefik.http.routers.niochat-backend-static.rule=Host(`app.niochat.com.br`) && PathPrefix(`/static/`)"
      - "traefik.http.routers.niochat-backend-static.entrypoints=websecure"
      - "traefik.http.routers.niochat-backend-static.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.niochat-backend-static.priority=200"
      - "traefik.http.routers.niochat-backend-static.service=niochat-backend-service"

      # Regra para WebSockets - PRIORIDADE MÁXIMA
      - "traefik.http.routers.niochat-backend-ws.rule=Host(`app.niochat.com.br`) && PathPrefix(`/ws/`)"
      - "traefik.http.routers.niochat-backend-ws.entrypoints=websecure"
      - "traefik.http.routers.niochat-backend-ws.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.niochat-backend-ws.priority=300"
      - "traefik.http.routers.niochat-backend-ws.service=niochat-backend-service"
      
      # Regra para Webhooks - PRIORIDADE MÁXIMA
      - "traefik.http.routers.niochat-backend-webhooks.rule=Host(`app.niochat.com.br`) && (PathPrefix(`/webhook/`) || PathPrefix(`/webhooks/`))"
      - "traefik.http.routers.niochat-backend-webhooks.entrypoints=websecure"
      - "traefik.http.routers.niochat-backend-webhooks.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.niochat-backend-webhooks.priority=250"
      - "traefik.http.routers.niochat-backend-webhooks.service=niochat-backend-service"

  # Frontend React - PORTA 8012
  niochat-frontend:
    image: ghcr.io/juniorssilvaa/niochat-frontend:latest
    networks:
      - nioNet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Regra para frontend - PRIORIDADE BAIXA (catch-all)
      - "traefik.http.routers.niochat-frontend.rule=Host(`app.niochat.com.br`)"
      - "traefik.http.routers.niochat-frontend.entrypoints=websecure"
      - "traefik.http.routers.niochat-frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.niochat-frontend.priority=1"
      - "traefik.http.routers.niochat-frontend.service=niochat-frontend-service"
      - "traefik.http.services.niochat-frontend-service.loadbalancer.server.port=8012"

  # Celery Worker para CSAT e tarefas assíncronas
  niochat-celery:
    image: ghcr.io/juniorssilvaa/niochat-backend:latest
    command: celery -A niochat worker -l info
    environment:
      - SECRET_KEY=OFfGQLqPs5osrBBnhOBdIfkjq1F6vpb74YoAWNkjwbY4BwTNK5
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgresql://niochat_user:E0sJT3wAYFuahovmHkxgy@postgres:5432/niochat
      - REDIS_URL=redis://niochat:E0sJT3wAYFuahovmHkxgy@154.38.176.17:6379/0
      - CELERY_BROKER_URL=redis://niochat:E0sJT3wAYFuahovmHkxgy@154.38.176.17:6379/0
      - CELERY_RESULT_BACKEND=redis://niochat:E0sJT3wAYFuahovmHkxgy@154.38.176.17:6379/0
    volumes:
      - niochat-media:/app/backend/media
    networks:
      - nioNet
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  nioNet:
    external: true
    name: nioNet

volumes:
  niochat-media:
    external: true
    name: niochat-media
  niochat-static:
    external: true
    name: niochat-static
  niochat-postgres:
    external: true
    name: niochat-postgres
