version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: niochat-postgres
    environment:
      - POSTGRES_DB=niochat
      - POSTGRES_USER=niochat_user
      - POSTGRES_PASSWORD=E0sJT3wAYFuahovmHkxgy
    volumes:
      - niochat-postgres:/var/lib/postgresql/data
    networks:
      - nioNet
    restart: unless-stopped

  # Backend Django
  niochat-backend:
    image: ghcr.io/juniorsilvacmd/niochat-backend:latest
    container_name: niochat-backend
    environment:
      - SECRET_KEY=OFfGQLqPs5osrBBnhOBdIfkjq1F6vpb74YoAWNkjwbY4BwTNK5
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgresql://niochat_user:E0sJT3wAYFuahovmHkxgy@postgres:5432/niochat
      - MEDIA_URL=/media/
      - STATIC_URL=/static/
      - LOG_LEVEL=DEBUG
    volumes:
      - niochat-media:/app/backend/media
      - niochat-static:/app/backend/staticfiles
    ports:
      - "8010:8000"  # ✅ MANTER PORTA 8010
    networks:
      - nioNet
    depends_on:
      - postgres
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # ✅ ROTA DA API via app.niochat.com.br
      - "traefik.http.routers.niochat-api.rule=Host(`app.niochat.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.niochat-api.entrypoints=websecure"
      - "traefik.http.routers.niochat-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.niochat-api.loadbalancer.server.port=8000"
      # ✅ ROTA DO ADMIN via app.niochat.com.br
      - "traefik.http.routers.niochat-admin.rule=Host(`app.niochat.com.br`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.niochat-admin.entrypoints=websecure"
      - "traefik.http.routers.niochat-admin.tls.certresolver=letsencrypt"
      - "traefik.http.services.niochat-admin.loadbalancer.server.port=8000"
      # ✅ ROTA DE MEDIA via app.niochat.com.br
      - "traefik.http.routers.niochat-media.rule=Host(`app.niochat.com.br`) && PathPrefix(`/media`)"
      - "traefik.http.routers.niochat-media.entrypoints=websecure"
      - "traefik.http.routers.niochat-media.tls.certresolver=letsencrypt"
      - "traefik.http.services.niochat-media.loadbalancer.server.port=8000"
      # ✅ ROTA DE TOKEN AUTH via app.niochat.com.br
      - "traefik.http.routers.niochat-token-auth.rule=Host(`app.niochat.com.br`) && PathPrefix(`/api-token-auth`)"
      - "traefik.http.routers.niochat-token-auth.entrypoints=websecure"
      - "traefik.http.routers.niochat-token-auth.tls.certresolver=letsencrypt"
      - "traefik.http.services.niochat-token-auth.loadbalancer.server.port=8000"

  # Frontend React
  niochat-frontend:
    image: ghcr.io/juniorsilvacmd/niochat-frontend:latest
    container_name: niochat-frontend
    ports:
      - "8012:3000"  # ✅ MANTER PORTA 8012
    networks:
      - nioNet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # ✅ ROTA DO FRONTEND (todas as outras requisições)
      - "traefik.http.routers.niochat-frontend.rule=Host(`app.niochat.com.br`)"
      - "traefik.http.routers.niochat-frontend.entrypoints=websecure"
      - "traefik.http.routers.niochat-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.niochat-frontend.loadbalancer.server.port=3000"
      # ✅ PRIORIDADE: API tem prioridade sobre frontend
      - "traefik.http.routers.niochat-api.priority=100"
      - "traefik.http.routers.niochat-admin.priority=100"
      - "traefik.http.routers.niochat-media.priority=100"
      - "traefik.http.routers.niochat-token-auth.priority=100"
      - "traefik.http.routers.niochat-frontend.priority=1"

networks:
  nioNet:
    external: true
    name: nioNet

volumes:
  niochat-media:
    driver: local
  niochat-static:
    driver: local
  niochat-postgres:
    driver: local
