version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: niochat-postgres
    environment:
      - POSTGRES_DB=niochat
      - POSTGRES_USER=niochat_user
      - POSTGRES_PASSWORD=E0sJT3wAYFuahovmHkxgy
    volumes:
      - niochat-postgres:/var/lib/postgresql/data
    networks:
      - nioNet
    restart: unless-stopped

  # Backend Django
  niochat-backend:
    image: ghcr.io/juniorsilvacmd/niochat-backend:latest
    container_name: niochat-backend
    environment:
      - SECRET_KEY=OFfGQLqPs5osrBBnhOBdIfkjq1F6vpb74YoAWNkjwbY4BwTNK5
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgresql://niochat_user:E0sJT3wAYFuahovmHkxgy@postgres:5432/niochat
      - MEDIA_URL=/media/
      - STATIC_URL=/static/
      - LOG_LEVEL=DEBUG
    volumes:
      - niochat-media:/app/backend/media
      - niochat-static:/app/backend/staticfiles
    ports:
      - "8010:8000"  # ✅ MANTER PORTA 8010
    networks:
      - nioNet
    depends_on:
      - postgres
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.niochat-backend.rule=Host(`api.niochat.com.br`)"
      - "traefik.http.routers.niochat-backend.entrypoints=websecure"
      - "traefik.http.routers.niochat-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.niochat-backend.loadbalancer.server.port=8000"
      # Admin route
      - "traefik.http.routers.niochat-admin.rule=Host(`admin.niochat.com.br`)"
      - "traefik.http.routers.niochat-admin.entrypoints=websecure"
      - "traefik.http.routers.niochat-admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.niochat-admin.service=niochat-backend"

  # Frontend React - SERVIDO DIRETAMENTE PELO TRAEFIK
  niochat-frontend:
    image: ghcr.io/juniorsilvacmd/niochat-frontend:latest
    container_name: niochat-frontend
    ports:
      - "8012:3000"  # ✅ MANTER PORTA 8012
    networks:
      - nioNet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.niochat-frontend.rule=Host(`app.niochat.com.br`)"
      - "traefik.http.routers.niochat-frontend.entrypoints=websecure"
      - "traefik.http.routers.niochat-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.niochat-frontend.loadbalancer.server.port=3000"
      # Rota para arquivos estáticos
      - "traefik.http.routers.niochat-static.rule=Host(`app.niochat.com.br`) && PathPrefix(`/assets/`)"
      - "traefik.http.routers.niochat-static.entrypoints=websecure"
      - "traefik.http.routers.niochat-static.tls.certresolver=letsencrypt"
      - "traefik.http.routers.niochat-static.service=niochat-frontend"

networks:
  nioNet:
    external: true
    name: nioNet

volumes:
  niochat-media:
    driver: local
  niochat-static:
    driver: local
  niochat-postgres:
    driver: local