name: Deploy NioChat to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: juniorssilvaa/niochat

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: niochat_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/frontend/package-lock.json

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node.js dependencies
      run: |
        cd frontend/frontend
        npm install --legacy-peer-deps

    - name: Run Python tests
      env:
        SECRET_KEY: test-secret-key
        DEBUG: True
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/niochat_test
        REDIS_URL: redis://localhost:6379
        CELERY_BROKER_URL: redis://localhost:6379/0
        CELERY_RESULT_BACKEND: redis://localhost:6379/0
      run: |
        cd backend
        python manage.py migrate
        python manage.py test

    - name: Build frontend
      run: |
        cd frontend/frontend
        npm run build

    - name: Lint Python code
      run: |
        pip install flake8
        flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 backend/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.backend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:${{ github.sha }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.frontend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:${{ github.sha }}

    - name: Cleanup dangling images
      run: docker image prune -f

  deploy:
    needs: [test, build-and-push]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Portainer
      env:
        PORTAINER_URL: https://portainer.niochat.com.br
        PORTAINER_API_KEY: ${{ secrets.PORTAINER_API_KEY }}
        BACKEND_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
        FRONTEND_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
      run: |\n        echo "Deploying to Portainer..."\n        echo "Backend image: $BACKEND_IMAGE"\n        echo "Frontend image: $FRONTEND_IMAGE"\n        \n        # Wait a moment for images to be available\n        sleep 10\n        \n        # Pegar ID da stack\n        STACK_ID=$(curl -s -H "X-API-Key: $PORTAINER_API_KEY" \\\\\n          "$PORTAINER_URL/api/stacks" | jq -r '.[] | select(.Name == "niochat") | .Id')\n\n        if [ -z "$STACK_ID" ] || [ "$STACK_ID" = "null" ]; then\n          echo "Stack 'niochat' not found. Please create it first in Portainer."\n          # List available stacks for debugging\n          echo "Available stacks:"\n          curl -s -H "X-API-Key: $PORTAINER_API_KEY" \\\\\n            "$PORTAINER_URL/api/stacks" | jq '.[].Name'\n          exit 1\n        fi\n\n        echo "Found stack: niochat (ID: $STACK_ID)"\n\n        # Buscar stack file atual\n        CURRENT_STACK=$(curl -s -H "X-API-Key: $PORTAINER_API_KEY" \\\\\n          "$PORTAINER_URL/api/stacks/$STACK_ID/file")\n\n        if [ -z "$CURRENT_STACK" ]; then\n          echo "Erro ao buscar stack atual"\n          exit 1\n        fi\n\n        # Atualizar imagens com latest - versão mais robusta\n        UPDATED_STACK=$(echo "$CURRENT_STACK" | jq '\n          .StackFileContent = (.StackFileContent |\n            gsub("ghcr\\\\.io/juniorssilvaa/niochat-backend:[^\\\\s]+"; "ghcr.io/juniorssilvaa/niochat-backend:latest") |\n            gsub("ghcr\\\\.io/juniorssilvaa/niochat-frontend:[^\\\\s]+"; "ghcr.io/juniorssilvaa/niochat-frontend:latest")\n          )\n        ')\n\n        # Forçar Portainer a atualizar a stack\n        RESPONSE=$(curl -s -X PUT \\\\\n          -H "X-API-Key: $PORTAINER_API_KEY" \\\\\n          -H "Content-Type: application/json" \\\\\n          --data "$UPDATED_STACK" \\\\\n          "$PORTAINER_URL/api/stacks/$STACK_ID?endpointId=1")\n\n        if echo "$RESPONSE" | grep -q "error"; then\n          echo "Error updating stack:"\n          echo "$RESPONSE"\n          exit 1\n        fi\n\n        echo "Stack updated successfully!"

    - name: Force image update
      run: |
        echo "Force pulling latest images..."
        # This step ensures that the latest images are pulled
        echo "If running on Portainer node, you might want to add commands to pull latest images"
        
    - name: Wait for deployment
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30

    - name: Health check
      run: |
        echo "Checking application health..."
        
        # Check backend health
        if curl -f -s "https://api.niochat.com.br/api/health/" > /dev/null; then
          echo "Backend is healthy"
        else
          echo "Backend health check failed"
        fi
        
        # Check frontend
        if curl -f -s "https://app.niochat.com.br/" > /dev/null; then
          echo "Frontend is healthy"
        else
          echo "Frontend health check failed"
        fi

    - name: Notify deployment
      run: |
        echo "NioChat deployed successfully!"
        echo "Frontend: https://app.niochat.com.br"
        echo "API: https://api.niochat.com.br"
        echo "Admin: https://admin.niochat.com.br"tigas tbm do GitHub Packages 