name: Deploy NioChat to Production

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: juniorsilvacmd/niochat

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: niochat_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/frontend/package-lock.json

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node.js dependencies
      run: |
        cd frontend/frontend
        npm install --legacy-peer-deps

    - name: Run Python tests
      env:
        SECRET_KEY: test-secret-key
        DEBUG: True
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/niochat_test
        REDIS_URL: redis://localhost:6379
        CELERY_BROKER_URL: redis://localhost:6379/0
        CELERY_RESULT_BACKEND: redis://localhost:6379/0
      run: |
        cd backend
        python manage.py migrate
        python manage.py test

    - name: Build frontend
      run: |
        cd frontend/frontend
        npm run build

    - name: Lint Python code
      run: |
        pip install flake8
        flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 backend/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.backend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.frontend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  validate-portainer:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Test connection with Portainer
        run: |
          curl -s -o /dev/null -w "%{http_code}" \
            -H "X-API-Key: ${{ secrets.PORTAINER_API_KEY }}" \
            https://portainer.niochat.com.br/api/endpoints/1/docker/containers/json

  deploy:
    needs: [test, build-and-push, validate-portainer]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Portainer
      env:
        PORTAINER_URL: https://portainer.niochat.com.br
        PORTAINER_API_KEY: ${{ secrets.PORTAINER_API_KEY }}
        BACKEND_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
        FRONTEND_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
      run: |
        echo "Deploying to Portainer..."
        echo "Backend image: $BACKEND_IMAGE"
        echo "Frontend image: $FRONTEND_IMAGE"
        
        # 1. REMOVER IMAGENS ANTIGAS
        echo "Removing old images..."
        
        # Listar e remover imagens antigas do backend
        OLD_BACKEND_IMAGES=$(curl -s -H "X-API-Key: $PORTAINER_API_KEY" \
          "$PORTAINER_URL/api/endpoints/1/docker/images/json" | \
          jq -r '.[] | select(.RepoTags[]? | contains("niochat-backend") and (contains("latest") | not)) | .Id')
        
        for image in $OLD_BACKEND_IMAGES; do
          echo "Removing old backend image: $image"
          curl -s -X DELETE -H "X-API-Key: $PORTAINER_API_KEY" \
            "$PORTAINER_URL/api/endpoints/1/docker/images/$image?force=true"
        done
        
        # Listar e remover imagens antigas do frontend
        OLD_FRONTEND_IMAGES=$(curl -s -H "X-API-Key: $PORTAINER_API_KEY" \
          "$PORTAINER_URL/api/endpoints/1/docker/images/json" | \
          jq -r '.[] | select(.RepoTags[]? | contains("niochat-frontend") and (contains("latest") | not)) | .Id')
        
        for image in $OLD_FRONTEND_IMAGES; do
          echo "Removing old frontend image: $image"
          curl -s -X DELETE -H "X-API-Key: $PORTAINER_API_KEY" \
            "$PORTAINER_URL/api/endpoints/1/docker/images/$image?force=true"
        done
        
        # 2. PULL DAS NOVAS IMAGENS
        echo "Pulling new images..."
        
        # Pull backend image
        curl -s -X POST \
          -H "X-API-Key: $PORTAINER_API_KEY" \
          -H "Content-Type: application/json" \
          -d "{\"fromImage\":\"$BACKEND_IMAGE\"}" \
          "$PORTAINER_URL/api/endpoints/1/docker/images/create?fromImage=$BACKEND_IMAGE"
        
        # Pull frontend image  
        curl -s -X POST \
          -H "X-API-Key: $PORTAINER_API_KEY" \
          -H "Content-Type: application/json" \
          -d "{\"fromImage\":\"$FRONTEND_IMAGE\"}" \
          "$PORTAINER_URL/api/endpoints/1/docker/images/create?fromImage=$FRONTEND_IMAGE"
        
        echo "Images pulled successfully!"
        
        # 3. ATUALIZAR STACK
        echo "Updating stack..."
        
        # Pegar ID da stack
        STACK_ID=$(curl -s -H "X-API-Key: $PORTAINER_API_KEY" \
          "$PORTAINER_URL/api/stacks" | jq -r '.[] | select(.Name == "niochat") | .Id')

        if [ -z "$STACK_ID" ] || [ "$STACK_ID" = "null" ]; then
          echo "Stack 'niochat' not found. Please create it first in Portainer."
          exit 1
        fi

        echo "Found stack: niochat (ID: $STACK_ID)"

        # Buscar stack file real
        CURRENT_STACK=$(curl -s -H "X-API-Key: $PORTAINER_API_KEY" \
          "$PORTAINER_URL/api/stacks/$STACK_ID/file")

        # Atualizar imagens no stack file
        UPDATED_STACK=$(echo "$CURRENT_STACK" | jq --arg backend "$BACKEND_IMAGE" --arg frontend "$FRONTEND_IMAGE" '
          .StackFileContent = (.StackFileContent |
            gsub("ghcr\\.io/juniorsilvacmd/niochat-backend:[^\\s]+"; $backend) |
            gsub("ghcr\\.io/juniorsilvacmd/niochat-frontend:[^\\s]+"; $frontend)
          )
        ')

        # Fazer PUT com novo stack file
        curl -s -X PUT \
          -H "X-API-Key: $PORTAINER_API_KEY" \
          -H "Content-Type: application/json" \
          --data "$UPDATED_STACK" \
          "$PORTAINER_URL/api/stacks/$STACK_ID?endpointId=1"

        echo "Stack updated successfully!"

    - name: Wait for deployment
      run: |
        echo "Waiting for deployment to complete..."
        sleep 45

    - name: Health check
      run: |
        echo "Checking application health..."
        
        # Check backend health
        if curl -f -s --retry 5 --retry-connrefused "https://app.niochat.com.br/api/auth/me/" > /dev/null; then
          echo "Backend is healthy"
        else
          echo "Backend health check failed"
          exit 1
        fi
        
        # Check frontend
        if curl -f -s --retry 5 --retry-connrefused "https://app.niochat.com.br/" > /dev/null; then
          echo "Frontend is healthy"
        else
          echo "Frontend health check failed"
          exit 1
        fi

    - name: Notify deployment
      run: |
        echo "NioChat deployed successfully!"
        echo "Frontend: https://app.niochat.com.br"
        echo "API: https://app.niochat.com.br/api/"
        echo "Superadmin: Junior / Semfim01@"
